name: "Snowflake Terraform Workflow - Production"

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  snowflake-terraform-production:
    name: "Snowflake Terraform Job"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Check Terraform Format and Correct
        id: fmt
        run: |
          terraform fmt -check
          terraform fmt
          terraform fmt -check

      - name: Terraform Init
        id: init
        env:
          TF_WORKSPACE: snowflake-production
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        env:
          TF_WORKSPACE: snowflake-production
        run: terraform apply -auto-approve
